<?php

/**
 * @file
 * Install file for migrate module.
 */

/**
 * Implements hook_install().
 */
function migrate_govcms_install() {
  // Set the migrate class.
  variable_set('wordpress_migrate_blog_class', 'GovCMSMigrateWordPress');
}

/**
 * Implements hook_uninstall().
 */
function migrate_govcms_uninstall() {
  // Delete the custom migrate class.
  variable_del('wordpress_migrate_blog_class');
}
